import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/NFT.module.css";
import HamburgerMenu from "../components/hamburgerMenu";
import { Input } from "@chakra-ui/react";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <header className={styles.header}>
        <HamburgerMenu numberBlocker={1} />
      </header>
      <div className={styles.container}>
        <main className={styles.main}>
          <h1>NFT Wrapping/ Unwrapping function</h1>
          <div className={styles.containerOutsideForm}>
            <h2>New Collection Smart Contract (wrapped)</h2>
            <Input placeholder='0x...' backgroundColor={'white'} />
          </div>

          <div className={styles.containerFormTop}>
            <h2>Collection Smart Contract (unwrapped)</h2>
            <Input placeholder='0x...' backgroundColor={'white'} />
          </div>
          <div className={styles.containerFormBottom}>
            <h2>Collection Smart Contract (unwrapped)</h2>
            <Input placeholder='0x...' backgroundColor={'white'} />
          </div>
        </main>
      </div>
      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
